# NOTE: "2" sets each rule to "error" level.
files:
  include: "_sass/*.scss"
  ignore: '_sass/fontawesome_*.scss'
options:
  merge-default-rules: true
rules:
  # Mixins
  mixins-before-declarations: 2
  # Line Spacing
  empty-line-between-blocks: 2
  # Disallows
  no-duplicate-properties: 2
  no-misspelled-properties: 2
  no-trailing-zero: 2
  # Style Guide
  property-sort-order: 2
  quotes: 2
  # Inner Spacing
  space-after-comma: 2
  space-before-brace: 2
  space-around-operator: 2
  # Final Items
  final-newline: 2
